version: "2"
volumes:
  control-data:
  gateway-data:
services:
  control:
    image: hortio/hortio-control-rpi:vdnh
    build: ./control
    volumes:
      - "control-data:/data"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    restart: always
    privileged: true
    depends_on:
      - owfs
  api:
    image: hortio/hortio-control-api:vdnh
    build: ./api
    volumes:
      - "control-data:/data"
    ports:
      - "80:5000"
    restart: always
  dashboard:
    image: hortio/hortio-web-dashboard:vdnh
    build: ./dashboard
    ports:
      - "8081:8081"
    restart: always
  owfs:
    image: hortio/hortio-owfs-rpi
    ports:
      - "4304:4304"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    restart: always
    privileged: true
  gateway:
    image: insideout/rpi-insideout
    build: ./gateway
    volumes:
      - "gateway-data:/root/.ssh"
    restart: always
