version: '2'
services:
  control:
    image: hortio/hortio-control-rpi:vdnh
    build: ./control
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    restart: always  
    privileged: true
    depends_on:
      - owfs
  dashboard:
    image: hortio/hortio-web-dashboard:vdnh
    build: ./dashboard
    ports:
      - "8081:443"    
    restart: always  
  ar:
    image: hortio/hortio-ar:vdnh
    ports:
      - "8082:443"    
    restart: always  
  owfs:
    image: hortio/hortio-owfs-rpi
    ports: 
      - "4304:4304"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    restart: always  
    privileged: true