version: '2'
services:
  control-api:
    image: hortio/hortio-control-api:vdnh
    privileged: true
    ports:
      - "8080:8080"
  control:
    image: hortio/hortio-control-rpi:vdnh
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
  dashboard:
    image: hortio/hortio-web-dashboard:vdnh
    ports:
      - "8081:80"    