version: '3'
services:
  control:
    image: hortio/hortio-control-rpi:vdnh
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
  watchtower:
    image: v2tec/watchtower:armhf-latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600